// import type { Metadata } from "next";
// import "../app/globals.css";
// import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
// import { ThemeProvider } from "@mui/material/styles";
// import { theme } from "@/helpers/uiHelpers";

// export const metadata: Metadata = {
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//         <AppRouterCacheProvider>
//           <ThemeProvider theme={theme}>
//             {children}
//           </ThemeProvider>
//         </AppRouterCacheProvider>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import "../app/globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import { theme } from "@/helpers/uiHelpers";
import NavBar from "./components/nabar";
import "../css/header.css"

export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
          <NavBar />

            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
